/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "1600px",
    },
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "pastel",
      "winter",
      "cupcake",
      "emerald",
      "corporate",
      "fantasy",
      "bumblebee",
      "cmyk",
      // "lofi",
      // "wireframe",
      // "lemonade",
      "acid",
      "autumn",
      "garden",
      "dark",
      "synthwave",
      "halloween",
      "forest",
      "night",
      "coffee",
      "business",
      "luxury",
      "dracula",
      // "black",
      "retro",
      "cyberpunk",
      "valentine",
      "aqua",
    ],
  },
};
