/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "pastel",
      "winter",
      "cupcake",
      "emerald",
      "corporate",
      "fantasy",
      "bumblebee",
      "cmyk",
      // "lofi",
      // "wireframe",
      // "lemonade",
      "acid",
      "autumn",
      "garden",
      "dark",
      "synthwave",
      "halloween",
      "forest",
      "night",
      "coffee",
      "business",
      "luxury",
      "dracula",
      // "black",
      "retro",
      "cyberpunk",
      "valentine",
      "aqua",
    ],
  },
};
